from .UNet.unet_segstrongc_projective import cfg as UNet_SegSTRONGC_Projective
from .UNet.unet_segstrongc_autoaugment import cfg as UNet_SegSTRONGC_AutoAugment
from .UNet.unet_segstrongc_elastic import cfg as UNet_SegSTRONGC_Elastic