from .UNet.unet_segstrongc_projective import cfg as UNet_SegSTRONGC_Projective
from .UNet.unet_segstrongc_autoaugment import cfg as UNet_SegSTRONGC_AutoAugment
from .UNet.unet_segstrongc_elastic import cfg as UNet_SegSTRONGC_Elastic
from .SETR_MLA.setr_mla_segstrongc_autoaugment import cfg as SETR_MLA_SegSTRONGC_AutoAugment
from .SETR_MLA.setr_mla_segstrongc_elastic import cfg as SETR_MLA_SegSTRONGC_Elastic
from .SETR_MLA.setr_mla_segstrongc_projective import cfg as SETR_MLA_SegSTRONGC_Projective